env_id: PongNoFrameskip-v4
wrappers:
  frame_skip: 4
  frame_stack: 4
  frame_size: 84
  grayscale: true
  clip_reward: true
  noop_max: 30

algo:
  name: dqn
  dueling: false
  n_step: 1
  gamma: 0.99
  tau: 1.0

optim:
  type: rmsprop
  lr: 6.25e-5
  alpha: 0.95
  eps: 0.01
  momentum: 0.0
  centered: false
  batch_size: 32
  grad_clip: 10.0

replay:
  type: uniform
  capacity: 1000000
  warmup_steps: 50000

epsilon:
  start: 1.0
  end: 0.1
  decay_steps: 1000000

train:
  total_frames: 100000          # короткий SMOKE
  target_update_interval: 10000 # важно для Atari
  save_every_frames: 50000

log:
  out_dir: D:/ML/LS/Deep_learning/Reinforcement_learning/project/artifacts_pong/tensorboard
  save_dir: D:/ML/LS/Deep_learning/Reinforcement_learning/project/artifacts_pong/checkpoints

model_name: dqn_rmsprop_smoke@100k
