env:
  frame_stack: 4
  minimal_actions: true
  seed: 42

model:
  dueling: true

algo:
  name: ddqn
  gamma: 0.99
  n_step: 1

replay:
  type: uniform
  capacity: 1000000

optim:
  name: adam
  lr: 0.00025

epsilon:
  start: 1.0
  end: 0.1
  decay_steps: 800000

train:
  total_frames: 600000
  warmup_steps: 20000
  batch_size: 32
  target_update_freq: 10000
  save_every: 200000

logging:
  tb_dir: artifacts_pong/tensorboard
  run_name: pong_ddqn_duel_uniform_smoke
  log_interval: 1000
  ckpt_dir: artifacts_pong/checkpoints
