env:
  frame_stack: 4
  minimal_actions: true
  seed: 42

model:
  dueling: true

algo:
  name: ddqn
  gamma: 0.99
  n_step: 3

replay:
  type: per
  capacity: 1000000
  alpha: 0.5
  beta_start: 0.4
  beta_end: 1.0

optim:
  name: adam
  lr: 0.00025

epsilon:
  start: 1.0
  end: 0.1
  decay_steps: 1500000   # медленнее сходимся -> больше эксплора
train:
  total_frames: 800000
  warmup_steps: 50000     # для PER лучше дольше прогреть буфер
  batch_size: 32
  target_update_freq: 10000
  save_every: 200000

logging:
  tb_dir: artifacts_pong/tensorboard
  run_name: pong_ddqn_duel_per_n3_800k_longeps
  log_interval: 1000
  ckpt_dir: artifacts_pong/checkpoints
