seed: 42
env_id: PongNoFrameskip-v4
total_frames: 1000000
eval_every_frames: 100000
eval_episodes: 20
agent:
  gamma: 0.99
  n_step: 1
  double_dqn: false
  dueling: false
  noisy_nets: false
  tau: 0.001
  lr: 0.00025
  grad_clip: 10.0
  use_amp: false
network:
  type: cnn
  channels:
  - 32
  - 64
  - 64
  convs:
  - - 32
    - 8
    - 4
  - - 64
    - 4
    - 2
  - - 64
    - 3
    - 1
  linear: 512
replay:
  type: uniform
  capacity: 100000
  batch_size: 32
  warmup_steps: 20000
  per_alpha: null
  per_beta_start: null
  per_beta_end: null
exploration:
  strategy: epsilon_greedy
  eps_start: 1.0
  eps_end: 0.05
  eps_decay_frames: 500000
wrappers:
  frame_skip: 4
  grayscale: true
  resize:
  - 84
  - 84
  frame_stack: 4
  clip_reward: true
  episodic_life: true
  noop_max: 30
  fire_reset: false
logging:
  log_dir: D:\ML\LS\Deep_learning\Reinforcement_learning\project\artifacts_pong\tensorboard
  tb: true
  mlflow: false
  video_every_eval: true
algo:
  name: dqn
  dueling: false
  n_step: 1
  gamma: 0.99
  tau: 0.001
optim:
  lr: 0.00025
  batch_size: 32
  grad_clip: 10.0
  amp: false
epsilon:
  start: 1.0
  end: 0.05
  decay_steps: 500000
train:
  total_frames: 1000000
  target_update_interval: 1
  eval_every_episodes: 20
  save_every_frames: 50_000
  render_eval: false
log:
  out_dir: D:\ML\LS\Deep_learning\Reinforcement_learning\project\artifacts_pong\tensorboard
  save_dir: D:\ML\LS\Deep_learning\Reinforcement_learning\project\artifacts_pong\checkpoints
  plots_dir: D:\ML\LS\Deep_learning\Reinforcement_learning\project\artifacts_pong\plots
  metrics_csv: D:\ML\LS\Deep_learning\Reinforcement_learning\project\artifacts_pong\metrics_pong.csv
